<?php

$title = 'Delete Film';
$url   = $this->url('film', ['action' => 'delete', 'id' => $this->id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($this->film->getTitle()) ?>" by
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int)$this->film->getId(); ?>"/>
        <input type="submit" class="btn btn-danger" name="del" value="Yes"/>
        <input type="submit" class="btn btn-success" name="del" value="No"/>
    </div>
</form>
